dataset: hd_epic

video:
  path: dataset/recordings/train/07

vrs_loader:
  ml_depth_pro_checkpoint_uri: conf/checkpoints/depthpro/depth_pro.pt
  vrs_slam_mapping_json: dataset/HD-EPIC/SLAM-and-Gaze/
  path: dataset/HD-EPIC/VRS/P01/P01-20240203-184045_anonymized.vrs

hand_detection_mediapipe:
  model_path: conf/checkpoints/mediapipe/hand_landmarker.task

hand_detection_yolo:
  model_path: conf/checkpoints/yolo/best.pt

hand_detection_hamer:
  checkpoint: conf/checkpoints/hamer_ckpts/checkpoints/hamer.ckpt
  body_detector: "vitdet"

segmentation:
  model_cfg: checkpoints/edgetam/edgetam.yaml
  model_path: checkpoints/edgetam/edgetam.pt
  imgsz: 1280
  conf: 0.005
  iou: 0.5
  zero_shot: True
  debug_dir: 
  vocab_path: 

graph_generator:


depth_generator:

camera:
  fx: 900
  fy: 900
  cx: 958.77
  cy: 539.25

pipeline:
  record_seg: False

training_generator:
  avion:
    pretrain_path: avion_pretrain_lavila_vitb_best.pt
    fine_tune_path: avion_finetune_cls_lavila_vitb_best.pt
  path: temp

ek100_loader:
  narration_csv_path: conf/ek100/EPIC100_train_small.csv
  video_base_path: dataset/EPIC-KITCHENS-100/videos
  frames_per_hypergraph: 16
  sliding_window_reduction: 8
  frame_sampling_interval: 1
