video:
  path: recordings/efe_kitchen_tea/2025-05-04--19-55-15

hand_detection_mediapipe:
  model_path: conf/checkpoints/mediapipe/hand_landmarker.task

hand_detection_yolo:
  model_path: conf/checkpoints/yolo/best.pt

hand_detection_hamer:
  checkpoint: conf/checkpoints/hamer_ckpts/checkpoints/hamer.ckpt
  body_detector: "vitdet"

segmentation:
  model_cfg: checkpoints/sam/sam2.1_hiera_l.yaml
  model_path: checkpoints/sam/sam2.1_hiera_large.pt
  imgsz: 1280
  conf: 0.1
  iou: 0.7
  zero_shot: True
  debug_dir: 
  vocab_path: 

graph_generator:


depth_generator:

camera:
  fx: 900
  fy: 900
  cx: 958.77
  cy: 539.25

pipeline:
  record_seg: False
